Careday/api

- careapp/migrations/0001_initial.py
- careapp/migrations/0002_auto_20151102_2126.py
- careapp/models.py
- careapp/templates/children_list.html
- careapp/templates/edit_child.html
- careapp/views.py
- careday/urls.py
> Ryanbranch2

- README.md
- careapp/models.py
> Bobbranch1

- careapp/admin.py
- careapp/forms.py
- careapp/migrations/0004_auto_20151102_2257.py
- careapp/models.py
- careapp/templates/careapp/base.html
- careapp/templates/careapp/children_list.html
- careapp/templates/careapp/edit_child.html
- careapp/views.py
- careday/settings.py
- careday/urls.py
added better admin views for child and dailyreport
changed timezone to eastern
> Ryanbranch3

- careapp/forms.py
- careapp/models.py
- careapp/templates/careapp/childs_list.html
- careapp/templates/careapp/daily_report.html
- careapp/templates/careapp/daily_report_initial.html
- careapp/views.py
- careday/urls.py
Daily Report with all fields can be displayed in a form and data is accepted onto Postico.
> Bobbranch2

- careapp/templates/careapp/daily_report.html
broke down daily report form to include individual form componants
> broke out daily report form

- careapp/templates/base.html
- careapp/templates/careapp/child_update_form.html
- careapp/templates/careapp/childs_list.html
- careapp/views.py
- careday/urls.py
added link to update child info
> added ability to update child

- careapp/admin.py
- careapp/forms.py
- careapp/migrations/0007_diapering.py
- careapp/models.py
- careapp/views.py
this is all of bobs code pertaining to the diaper table
> took bobs code about diapering and recommited

- careapp/forms.py
- careapp/migrations/0005_auto_20151103_1219.py
- careapp/templates/careapp/diapering_form.html
- careapp/templates/children_list.html
- careapp/views.py
- careday/urls.py
Complete, working diapering model.
> diapering views/templates

- careapp/admin.py
- careapp/migrations/0002_eating_sleeping.py
- careapp/models.py
Ryan and Terry, please migrate after this pull request
> Eating and Sleeping models and admin

- careapp/forms.py
- careapp/templates/careapp/diapering_form.html
- careapp/templates/careapp/sleeping_form.html
- careapp/views.py
- careday/urls.py
Updated sleeping views, url, template and html.   Minor revisions to diaper html and view.
> Bobsleeping

- careapp/templates/base.html
- careapp/templates/careapp/daily_report_initial.html
- careapp/templates/careapp/daily_report_list.html
- careapp/templates/careapp/dailyreport_update_form.html
- careapp/views.py
- careday/urls.py
Consolidated branch focused on Daily Report revisions.
> Bobrevisedailyreport

- careday/settings.py
this is a quick fix for the successful login to redirect to childs page
> quick fix for successful login redirect to childs page

- careapp/templates/base.html
- careapp/templates/careapp/daily_report.html
- careapp/templates/login.html
- careapp/templates/toggle_login.html
- careapp/views.py
the nav admin login works and redirects to login.html  page on fail.
> admin login works and redirects to 2ndary login page on fail

- careapp/static/style.css
- careapp/templates/base.html
- careapp/templates/careapp/daily_report.html
- careapp/views.py
all the forms are on the report page
> Ryan expand formsets1

- careapp/forms.py
- careapp/models.py
- careapp/templates/careapp/daily_report.html
- careapp/templates/careapp/diapering_form.html
- careapp/views.py
- careday/settings.py
- careday/urls.py
added lots of meta tags for better readability and automatic sorting.
children are sorted by first_name.
diapering, sleeping and eating are sorted by the dailyreport.date and then from earliest to latest.
dailyreports are sorted by date with most recent first.
> Ryan form submission added lots of meta tags

- careapp/templates/base.html
- careapp/templates/careapp/archive_child.html
- careapp/templates/careapp/archive_date.html
- careapp/views.py
- careday/urls.py
this adds the 2 archive pages to urls and views
> Ryan archive 1

- careapp/templates/careapp/archive_child.html
- careapp/templates/careapp/archive_date.html
- careapp/views.py
Some revision to archive/child and archive/date views (no great breakthrough but worth updating).  Name was intended to address url assignment; no changes to url in this branch.
> Bob url draft

- careapp/static/style.css
- careapp/templates/careapp/bobchild_list.html
- careapp/templates/careapp/child_update_form.html
- careapp/templates/careapp/edit_child.html
reformatting the child management page
added bottom margin to roster-images 
and tried to center the add button
added in some javascript to make delete confirmation popup in child update form
> Ryan fixin management page

- careapp/views.py
- careday/urls.py
this seems to fix submitting our 4 main forms on report page
> Ryan another form fix attempt

- careday/heroku_settings.py
> Revert "heroku static file issue"
